export const ADD_INGREDIENTS = 'ADD_INGREDIENTS';
export const REMOVE_INGREDIENTS = 'REMOVE_INGREDIENTS';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const ERR_SET_INGREDIENTS = 'ERR_SET_INGREDIENTS';


export const MAKE_ORDER = 'MAKE_ORDER';
export const MAKE_ORDER_IN_PROGRESS = 'MAKE_ORDER_IN_PROGRESS';
export const MAKE_ORDER_SUCCESS = 'MAKE_ORDER_SUCCESS';
export const MAKE_ORDER_FAIL = 'MAKE_ORDER_FAIL';